### ISSUE TITLE
Add product integral

### ISSUE THREAD

**Issue by sebschub** [sebschub/MdSymbol#2]
Add a product integral like the one [here](http://www.ctan.org/tex-archive/fonts/prodint).

**Comment by sebschub** [comment]
I added a version in c4c0095ecdf71d55fc49ce8b4957d79cdccd5cb6
It looks this way (together with the normal product symbol):
![product integral](http://dl.dropbox.com/u/41227811/prodi.png)
Is that ok? Should it be fancier?

**Comment by aboruvka** [comment]
Looks fine to my untrained eye, but is it different enough from \prod? The product integral is an analog of integration, but for products. So if you don't find the symbols different enough you could add some slant - something akin to Myriad's (lowercase) \pi, but of equal weight and size to \prod. BTW: Adding \coprodi is sort of like offering an upside-down integral - I don't think it's needed.

**Comment by sebschub** [comment]
I guess you would place the limits on top and below the symbol, right? I tried to add a slant to the symbol similar to the integral sign or a pi. However, due to the large height of the symbol, the top part of the symbol is considerably more right than the lower part resulting in an ugly placement of the limits. I'll try other designs...

**Comment by aboruvka** [comment]
The limits can be placed in different spots: top-centre, bottom-centre, top-right, bottom-right. To keep things simple you could just allow the last three locations. It often matters whether the interval given by the limits is closed or open - typically they're of the form (s, t]. This interval can be indicated neatly bottom-centre.

**Comment by sebschub** [comment]
Sorry for the wait. What do you think of the following version?
![product integral](http://dl.dropbox.com/u/41227811/prodi2.png)
Furthermore, I think I'll keep the \coprodi for now, enough slots in the encoding still free.

**Comment by aboruvka** [comment]
Looks good. Thanks!

**Comment by sebschub** [comment]
Ok, closing this with 8f2d7acdedd766c69e6f5f76322b8aee1b42cc23. I'll go on checking older line width adjustments and then I'll upload the new version in the redthick branch to CTAN.
